const jsonData = {
    "isAvailable": true,
    "titleJobs": ["Web Developer", "Graphic Designer", "Game Developer"],
    "skills": [
        "Adobe Creative Suite",
        "Adobe Illustrator",
        "Adobe InDesign",
        "Adobe Photoshop",
        "Adobe XD",
        "Angular",
        "Back-End",
        "Blender",
        "Bootstrap",
        "C",
        "C#",
        "C++",
        "CSS",
        "Django",
        "Figma",
        "Front-End",
        "Full-Stack",
        "Game Development",
        "Git",
        "HTML",
        "Java",
        "JavaScript",
        "Kotlin",
        "Microsoft Office Suite",
        "PHP",
        "Python",
        "React",
        "SASS",
        "SQL",
        "Unity",
        "Vue",
        "Web Development",
        "3D Modeling"
    ],
    "jobs": [
        {
            "name": "EasilyAmused",
            "location": "Florida, USA (Remote)",
            "position": "Graphic Designer & Front-End Developer",
            "description": "Redesigned web pages and built a large collection of widgets for a WordPress company that sells custom themes.",
        },
        {
            "name": "SENSE4FIT",
            "location": "Romania (Remote)",
            "position": "Full-Stack Developer",
            "description": "I built the website for a fitness-centric startup dealing in cryptocurrency & NFTs.",
        },
        {
            "name": "EduKiwi",
            "location": "Romania (Remote)",
            "position": "Front-End Developer & Graphic Designer",
            "description": "Worked with a marketing agency where I coded and did maintenance on promotional websites. I also designed social media content for various clients.",
        },
        {
            "name": "Canon",
            "location": "Romania (Remote)",
            "position": "Front-End Developer",
            "description": "Created tools and widgets that would help service users customize their experience or make their workflow more efficient. Most of the work was done in Angular 5.",
        },
        {
            "name": "Grupo9",
            "location": "Belgium (Remote)",
            "position": "Full-Stack Developer & Graphic Designer",
            "description": "Worked with a server hosting company where I redesigned and developed the dashboard that their clients used. The project required vanilla languages only, such as HTML, CSS, PHP, and plain JavaScript.",
        },
    ]
};